dataset:
  target_name: "MNIST"
  target_folder: "data/mnist_v2"

  # aux_name: "texture"
  # aux_folder: "data/texture_mnist_32"

  aux_name: "MNIST_Gaps"
  aux_folder: "data/mnist_skip_32"

  rng_seed: 42
  batch_size: 64
  base_sample_ratio: .1 # .2 means 20% of all train samples go to base

save_locations:
  model_folder: "models"
  file_folder: "files"
  image_folder: "images"
  logs_folder : "logs"

classifier:
  model: "resnet9"
  identifier: "MNIST+MNIST_Skip" # unique identifier for the set of models
  num_epochs: 100


unet:
  loss: "ebsw"
  num_epochs: 70

verbose: false