dataset:
  target_name: "smear"
  target_folder: "data/cifar10_smear_v2_32"

  # aux_name: "texture"
  # aux_folder: "data/texture_mnist_32"

  aux_name: "none"
  aux_folder: "data/cifar10_v2"

  rng_seed: 72
  batch_size: 64
  base_sample_ratio: .1 # .2 means 20% of all train samples go to base

save_locations:
  model_folder: "models"
  file_folder: "files"
  image_folder: "images"
  logs_folder : "logs"

classifier:
  model: "resnet9"
  identifier: "Smear+C10" # unique identifier for run
  num_epochs: 100


unet:
  loss: "ebsw"
  num_epochs: 70

verbose: true