dataset:
  name: "mnist"
  base_ds: "skip"
  aux_ds: "none"
  rng_seed: 72
  batch_size: 64
  base_sample_ratio: .2 # .2 means 20% of all train samples go to base

save_locations:
  model_folder: "models"
  file_folder: "files"
  image_folder: "images"

classifier:
  identifier: "tiny" # unique identifier for the set of models
  num_filters: [8, 16]
  kernel_size: [3, 3]
  stride: [1, 1]
  padding: [1, 1]
  mlp_layer_sizes: [32]
  num_classes: 10

unet:
  loss: "ebsw"